export const RESTAURANTS = [
  "FRI menza",
  "Rožna dolina menza",
  "BF menza",
  "FE menza",
  "Menza na Kardeljevi",
  "Menza Poljane",
  "ŠOU menza",
  "Menza UM",
  "Menza UP",
  "Slorest",
  "Interspar restavracija",
  "Deli",
  "Hana",
  "Kompot",
  "Kodila",
  "Emonska klet",
  "Figovec",
  "Kavarna Tiskarna",
  "Le Petit Café",
  "Čerin",
  "Gostilna Šestica",
  "Nebotičnik",
  "Pop's Place",
  "Druga violina",
  "Barbarella",
  "Olimpija",
  "Gostilna Dela",
  "Restavracija 2000",
  "TaBar",
  "Falafel Ljubljana",
  "Nobel Burek",
  "Hood Burger",
  "Döner Kebab",
  "Pasta House",
  "Sushi Mama",
  "Moji štruklji",
  "Stari Pisker (Maribor)",
  "Restavracija Ilich (Maribor)",
  "Menza Pekarna (Maribor)",
  "Restavracija Stil (Maribor)",
  "Gostilna Pri Lešniku (Maribor)",
  "Restavracija Rožmarin (Koper)",
  "Menza UP (Koper)",
];
