export const UNIVERSITIES: Record<string, string[]> = {
  "Univerza v Ljubljani": [
    "Akademija za glasbo",
    "Akademija za gledališče, radio, film in televizijo",
    "Akademija za likovno umetnost in oblikovanje",
    "Biotehniška fakulteta",
    "Ekonomska fakulteta",
    "Fakulteta za arhitekturo",
    "Fakulteta za družbene vede",
    "Fakulteta za elektrotehniko",
    "Fakulteta za farmacijo",
    "Fakulteta za gradbeništvo in geodezijo",
    "Fakulteta za kemijo in kemijsko tehnologijo",
    "Fakulteta za matematiko in fiziko",
    "Fakulteta za računalništvo in informatiko",
    "Fakulteta za socialno delo",
    "Fakulteta za strojništvo",
    "Fakulteta za šport",
    "Fakulteta za upravo",
    "Filozofska fakulteta",
    "Medicinska fakulteta",
    "Naravoslovnotehniška fakulteta",
    "Pedagoška fakulteta",
    "Pravna fakulteta",
    "Teološka fakulteta",
    "Veterinarska fakulteta",
    "Zdravstvena fakulteta",
  ],
  "Univerza v Mariboru": [
    "Ekonomsko-poslovna fakulteta",
    "Fakulteta za elektrotehniko, računalništvo in informatiko",
    "Fakulteta za energetiko",
    "Fakulteta za gradbeništvo, prometno inženirstvo in arhitekturo",
    "Fakulteta za kemijo in kemijsko tehnologijo",
    "Fakulteta za kmetijstvo in biosistemske vede",
    "Fakulteta za logistiko",
    "Fakulteta za naravoslovje in matematiko",
    "Fakulteta za organizacijske vede",
    "Fakulteta za strojništvo",
    "Fakulteta za turizem",
    "Fakulteta za varnostne vede",
    "Fakulteta za zdravstvene vede",
    "Filozofska fakulteta",
    "Medicinska fakulteta",
    "Pedagoška fakulteta",
    "Pravna fakulteta",
  ],
  "Univerza na Primorskem": [
    "Fakulteta za humanistične študije",
    "Fakulteta za management",
    "Fakulteta za matematiko, naravoslovje in informacijske tehnologije",
    "Fakulteta za turistične študije - Turistica",
    "Fakulteta za vede o zdravju",
    "Pedagoška fakulteta",
  ],
  "Univerza v Novi Gorici": [
    "Fakulteta za aplikativno naravoslovje",
    "Fakulteta za humanistiko",
    "Fakulteta za podiplomski študij",
    "Fakulteta za vinogradništvo in vinarstvo",
    "Poslovno-tehniška fakulteta",
    "Visoka šola za umetnost",
  ],
  "Univerza v Novem mestu": [
    "Fakulteta za ekonomijo in informatiko",
    "Fakulteta za strojništvo",
    "Fakulteta za zdravstvene vede",
  ],
};

export const UNIVERSITY_NAMES = Object.keys(UNIVERSITIES);
