export const UNIVERSITIES: Record<string, string[]> = {
  "Univerza v Ljubljani": [
    "Akademija za glasbo",
    "Akademija za gledališče, radio, film in televizijo",
    "Akademija za likovno umetnost in oblikovanje",
    "Biotehniška fakulteta",
    "Ekonomska fakulteta",
    "Fakulteta za arhitekturo",
    "Fakulteta za družbene vede",
    "Fakulteta za elektrotehniko",
    "Fakulteta za farmacijo",
    "Fakulteta za gradbeništvo in geodezijo",
    "Fakulteta za kemijo in kemijsko tehnologijo",
    "Fakulteta za matematiko in fiziko",
    "Fakulteta za računalništvo in informatiko",
    "Fakulteta za socialno delo",
    "Fakulteta za strojništvo",
    "Fakulteta za šport",
    "Fakulteta za upravo",
    "Filozofska fakulteta",
    "Medicinska fakulteta",
    "Naravoslovnotehniška fakulteta",
    "Pedagoška fakulteta",
    "Pravna fakulteta",
    "Teološka fakulteta",
    "Veterinarska fakulteta",
    "Zdravstvena fakulteta",
  ],
  "Univerza v Mariboru": [
    "Ekonomsko-poslovna fakulteta",
    "Fakulteta za elektrotehniko, računalništvo in informatiko",
    "Fakulteta za energetiko",
    "Fakulteta za gradbeništvo, prometno inženirstvo in arhitekturo",
    "Fakulteta za kemijo in kemijsko tehnologijo",
    "Fakulteta za kmetijstvo in biosistemske vede",
    "Fakulteta za logistiko",
    "Fakulteta za naravoslovje in matematiko",
    "Fakulteta za organizacijske vede",
    "Fakulteta za strojništvo",
    "Fakulteta za turizem",
    "Fakulteta za varnostne vede",
    "Fakulteta za zdravstvene vede",
    "Filozofska fakulteta",
    "Medicinska fakulteta",
    "Pedagoška fakulteta",
    "Pravna fakulteta",
  ],
  "Univerza na Primorskem": [
    "Fakulteta za humanistične študije",
    "Fakulteta za management",
    "Fakulteta za matematiko, naravoslovje in informacijske tehnologije",
    "Fakulteta za turistične študije - Turistica",
    "Fakulteta za vede o zdravju",
    "Pedagoška fakulteta",
  ],
  "Univerza v Novi Gorici": [
    "Fakulteta za aplikativno naravoslovje",
    "Fakulteta za humanistiko",
    "Fakulteta za podiplomski študij",
    "Fakulteta za vinogradništvo in vinarstvo",
    "Poslovno-tehniška fakulteta",
    "Visoka šola za umetnost",
  ],
  "Univerza v Novem mestu": [
    "Fakulteta za ekonomijo in informatiko",
    "Fakulteta za strojništvo",
    "Fakulteta za zdravstvene vede",
  ],
  "Nova univerza": [
    "Evropska pravna fakulteta",
    "Fakulteta za državne in evropske študije",
    "Fakulteta za slovenske in mednarodne študije",
  ],
  "Univerza Alma Mater Europaea": [
    "Akademija za ples",
    "Fakulteta ECM",
    "Institutum Studiorum Humanitatis, fakulteta za humanistični študij",
  ],
  "Samostojni visokošolski zavodi": [
    "AREMA - Visoka šola za logistiko in management",
    "AVA - Akademija za vizualne umetnosti",
    "B2 Visoka šola za poslovne vede, Ljubljana",
    "B&B visoka šola za trajnostni razvoj, Kranj",
    "DOBA, Fakulteta za uporabne poslovne in družbene študije Maribor",
    "EMUNI University",
    "ERUDIO Visokošolsko središče",
    "Fakulteta za dizajn",
    "Fakulteta za industrijski inženiring, Novo mesto",
    "Fakulteta za informacijske študije v Novem Mestu",
    "Fakulteta za komercialne in poslovne vede, Celje",
    "Fakulteta za organizacijske študije, Novo mesto",
    "Fakulteta za pravo in ekonomijo",
    "Fakulteta za tehnologijo polimerov, Slovenj Gradec",
    "Fakulteta za uporabne družbene študije v Novi Gorici",
    "Fakulteta za varstvo okolja, Velenje",
    "Fakulteta za zdravstvene in socialne vede, Slovenj Gradec",
    "Fakulteta za zdravstvene vede v Celju",
    "Fakulteta za zdravstvo Angele Boškin",
    "GEA College – Fakulteta za podjetništvo, Ljubljana",
    "IAM Visoka šola za multimedije, Ljubljana",
    "IBS Mednarodna poslovna šola",
    "IEDC - Poslovna šola Bled",
    "Mednarodna fakulteta za družbene in poslovne študije, Celje",
    "Mednarodna podiplomska šola Jožefa Štefana",
    "MLC - Fakulteta za management in pravo Ljubljana",
    "NOA",
    "Podiplomska šola ZRC SAZU",
    "Šola za risanje in slikanje, Ljubljana",
    "Visoka šola na Ptuju",
    "Visoka šola za gradbeno inženirstvo Kranj",
    "Visoka šola za management Bled",
    "Visoka šola za proizvodno inženirstvo",
    "Visoka šola za računovodstvo in finance, Ljubljana",
    "Visoka šola za upravljanje podeželja Grm Novo Mesto",
    "Visokošolski zavod Fizioterapevtika",
    "VIST - Fakulteta za aplikativne vede",
  ],
};

export const UNIVERSITY_NAMES = Object.keys(UNIVERSITIES);
